import type { NextPage } from "next";
import Head from "next/head";
import { createContext, useState } from "react";
import Board from "./components/Board";
import Keyboard from "./components/Keyboard";
import { defaultBoard } from "./components/WordsHelper";

export const AppContext = createContext<any>(defaultBoard);

const Home: NextPage = () => {
	const [board, setBoard] = useState(defaultBoard);

	return (
		<div className=" bg-neutral-900 text-white h-screen">
			<Head>
				<title>Wordle clone</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<AppContext.Provider value={{ board, setBoard }}>
					<Board />
					<Keyboard />
				</AppContext.Provider>
			</main>

			<footer></footer>
		</div>
	);
};

export default Home;
